aliases:
  - &store_test_results
    path: /tmp/test-results

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          environment:
            MOCHA_FILE: /tmp/test-results/mocha.xml
          name: run mocha tests
          command: |
            mkdir /tmp/test-results
            npm run test:ci
      - store_test_results: *store_test_results
