aliases:
  - &dir ~/repo
  - &defaults
    working_directory: *dir
    docker:
      - image: circleci/node:lts
  - &attach_workspace
    attach_workspace:
      at: *dir
  - &cache-key
    key: dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: *dir
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *cache-key
      - run: npm install
      - save_cache:
          <<: *cache-key
          paths:
            - ./node_modules
      - run:
          environment:
            MOCHA_FILE: /tmp/test-results/mocha.xml
          name: run mocha tests
          command: |
            mkdir /tmp/test-results
            npm run test:ci
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: *dir
          paths:
            - node_modules

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - checkout
      - run: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test