version: 2.1

################################
# Aliases

aliases:
  - &dir ~/repo
  - &attach_workspace
    attach_workspace:
      at: *dir
  - &cache-key dependency-cache-{{ checksum "package.json" }}
  - &cache-key-fallback dependency-cache-

################################
# Executors

executors:
  node:
    working_directory: *dir
    docker:
      - image: cimg/node:lts


################################
# Jobs

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: *dir
          paths:
            - .

  test:
    executor: node
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - *cache-key
            - *cache-key-fallback
      - run: npm install
      - save_cache:
          key: *cache-key
          paths:
            - ./node_modules
      - run:
          environment:
            MOCHA_FILE: /tmp/test-results/mocha.xml
          name: run mocha tests
          command: |
            mkdir /tmp/test-results
            npm run test:ci
      - store_test_results:
          path: /tmp/test-results
      - persist_to_workspace:
          root: *dir
          paths:
            - node_modules

  release:
    executor: node
    steps:
      - *attach_workspace
      - checkout
      - run: npm run semantic-release


################################
# Workflows

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
